### ISSUE TITLE
How to customize the time format in the log?

### ISSUE THREAD

**Issue by zxyao145** [api7/gopkg#4]
Hi, I want to customize the time format in the log, it seems that this configuration item is unavailable at present?

**Comment by tokers** [comment]
Yes, it cannot customize the time format right now.

**Comment by zxyao145** [comment]
@tokers Hi, can I create a PR for this issue?

**Comment by tokers** [comment]
Sure!

**Comment by zxyao145** [comment]
@tokers Thanks, I'll give it a try
